### ISSUE TITLE
Check out 'conda'

### ISSUE THREAD

**Issue by alexbw** [uluadist/lua-pkg#1]
It's a package manager that solves a number of the problems you're working on. I've been working on conda recipes for a lot of the Torch ecosystem here: https://github.com/alexbw/conda-lua-recipes. I've done no work for it on Windows yet, but it's relatively simple to get going.

**Comment by stepelu** [comment]
Thank you, I was not aware of the conda framework. It is similar in some aspects indeed.
It is a much heavier framework though, and it would not solve by itself some of the issues I had to deal with.
